[phases.setup]
nixPkgs = ["nodejs_20", "python313"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn datafalcon_main.wsgi --bind 0.0.0.0:$PORT --log-file -"